[2022-12-25 17:50:04] [INFO    ] discord.client: logging in using static token
[2022-12-25 17:50:05] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 54ae219a331cf591b4a6e89f0271cd72).
[2022-12-25 17:50:25] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'add_code'
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\app_commands\commands.py", line 851, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "c:\Users\Owen\Personal\General\Discord\student-test.py", line 106, in add_code
    messageID = await getStockpile(interaction.channel, stockpiles)
  File "c:\Users\Owen\Personal\General\Discord\student-test.py", line 40, in getStockpile
    messages = await channel.history().flatten()
AttributeError: 'async_generator' object has no attribute 'flatten'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\app_commands\tree.py", line 1240, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Python310\lib\site-packages\discord\app_commands\commands.py", line 876, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Python310\lib\site-packages\discord\app_commands\commands.py", line 869, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'add_code' raised an exception: AttributeError: 'async_generator' object has no attribute 'flatten'
[2022-12-25 18:26:44] [WARNING ] discord.gateway: Shard ID None has stopped responding to the gateway. Closing and restarting.
[2022-12-25 18:26:45] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2022-12-25 18:26:50] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ce1ba5a7990ab4668b7a3a2989750527).
